# Generated by Django 6.0.4 on 2026-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_herobanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='categoryrequest',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='FaShoppingBasket', max_length=100),
        ),
        migrations.AddField(
            model_name='categoryrequest',
            name='icon',
            field=models.CharField(default='FaShoppingBasket', max_length=100),
        ),
    ]
