# Generated by Django 6.0.4 on 2026-05-08 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_category_image_remove_categoryrequest_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_type',
            field=models.CharField(choices=[('iconify', 'Iconify'), ('uploaded_svg', 'Uploaded SVG'), ('uploaded_image', 'Uploaded Image'), ('legacy', 'Legacy React-Icons')], default='iconify', max_length=20),
        ),
        migrations.AddField(
            model_name='categoryrequest',
            name='icon_type',
            field=models.CharField(choices=[('iconify', 'Iconify'), ('uploaded_svg', 'Uploaded SVG'), ('uploaded_image', 'Uploaded Image'), ('legacy', 'Legacy React-Icons')], default='iconify', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='mdi:shopping', max_length=255),
        ),
        migrations.AlterField(
            model_name='categoryrequest',
            name='icon',
            field=models.CharField(default='mdi:shopping', max_length=255),
        ),
        migrations.CreateModel(
            name='IconAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon_type', models.CharField(choices=[('uploaded_svg', 'SVG'), ('uploaded_image', 'Image')], max_length=20)),
                ('file', models.FileField(upload_to='category-icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
