# Generated by Django 6.0.4 on 2026-05-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='offers', to='myapp.product'),
        ),
    ]
