# Generated by Django 6.0.4 on 2026-05-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0025_offer_discount_percent_offer_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
    ]
