# Generated by Django 6.0.4 on 2026-05-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0029_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorprofile",
            name="shop_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
