# Generated by Django 6.0.4 on 2026-05-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0030_alter_vendorprofile_shop_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorprofile",
            name="address",
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
