# Generated by Django 6.0.4 on 2026-05-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0031_remove_vendorprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="youtube_url",
            field=models.CharField(
                blank=True,
                help_text="YouTube Video URL (For Right Banner)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
    ]
