# Generated by Django 6.0.4 on 2026-05-28 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0032_banner_youtube_url_alter_banner_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gst_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=18.0,
                        help_text="GST percentage applied on platform fee",
                        max_digits=5,
                    ),
                ),
                (
                    "platform_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Platform fee percentage applied on base order amount",
                        max_digits=5,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile number must be exactly 10 digits and start with 6, 7, 8, or 9.",
                        regex="^[6-9]\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile number must be exactly 10 digits and start with 6, 7, 8, or 9.",
                        regex="^[6-9]\\d{9}$",
                    )
                ],
            ),
        ),
    ]
