# Generated by Django 6.0.4 on 2026-06-11 05:46

from django.db import migrations, models

def migrate_existing_gst_data(apps, schema_editor):
    Category = apps.get_model("myapp", "Category")
    GSTCategory = apps.get_model("myapp", "GSTCategory")
    Product = apps.get_model("myapp", "Product")
    ProductVariant = apps.get_model("myapp", "ProductVariant")
    import decimal

    # Create GST Category mappings
    percentages = Category.objects.values_list('gst_percentage', flat=True).distinct()
    gst_cat_map = {}
    for pct in percentages:
        if pct is None:
            pct_val = decimal.Decimal('18.00')
        else:
            pct_val = decimal.Decimal(str(pct))
        
        gst_cat_name = f"GST {pct_val}%"
        # Avoid duplicates
        gst_cat, created = GSTCategory.objects.get_or_create(
            gst_percentage=pct_val,
            defaults={'name': gst_cat_name}
        )
        gst_cat_map[pct] = gst_cat

    # Assign categories to their corresponding GSTCategory
    for category in Category.objects.all():
        pct = category.gst_percentage
        gst_cat = gst_cat_map.get(pct)
        if gst_cat:
            gst_cat.categories.add(category)

    # Recalculate GST fields for all products
    for product in Product.objects.all():
        category = product.category
        gst_pct = decimal.Decimal('0.00')
        if category:
            gst_cat = category.gst_categories.first()
            if gst_cat:
                gst_pct = gst_cat.gst_percentage
        
        product.base_price = product.price
        product.gst_percentage = gst_pct
        product.gst_amount = round(product.base_price * gst_pct / decimal.Decimal('100.00'), 2)
        product.final_price = product.base_price + product.gst_amount
        product.save()

    # Recalculate GST fields for all product variants
    for variant in ProductVariant.objects.all():
        product = variant.product
        category = product.category
        gst_pct = decimal.Decimal('0.00')
        if category:
            gst_cat = category.gst_categories.first()
            if gst_cat:
                gst_pct = gst_cat.gst_percentage
        
        variant.base_price = variant.price
        variant.gst_percentage = gst_pct
        variant.gst_amount = round(variant.base_price * gst_pct / decimal.Decimal('100.00'), 2)
        variant.final_price = variant.base_price + variant.gst_amount
        variant.save()


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0034_category_gst_percentage_order_cgst_order_igst_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GSTCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "gst_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="GST percentage for assigned categories",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Product categories assigned to this GST rate",
                        related_name="gst_categories",
                        to="myapp.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "GST Categories",
                "ordering": ["gst_percentage"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Mirrors 'price' field for clarity",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="final_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Calculated: base_price + gst_amount",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gst_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Calculated: base_price × gst_percentage / 100",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gst_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Auto-set from GST Category",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="base_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="final_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="gst_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="gst_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Base price without GST", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Base price without GST", max_digits=10
            ),
        ),
        migrations.RunPython(
            migrate_existing_gst_data,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="category",
            name="gst_percentage",
        ),
    ]

