# Generated by Django 6.0.4 on 2026-06-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0035_remove_category_gst_percentage_product_base_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_charge",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_charge_gst",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="platformconfiguration",
            name="shipping_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Flat shipping charge applied on orders",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="platformconfiguration",
            name="gst_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=18.0,
                help_text="GST percentage applied on platform fee and shipping charge",
                max_digits=5,
            ),
        ),
    ]
