# Generated by Django 6.0.4 on 2026-07-08 06:52

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_remove_platformconfiguration_gst_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[800, 1000], upload_to='review_images/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.productreview')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
